// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GrpcService.proto

package GrpcServices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestInt struct {
	OutInt               string   `protobuf:"bytes,1,opt,name=outInt" json:"outInt,omitempty"`
	BitmapSeq            string   `protobuf:"bytes,5,opt,name=bitmapSeq" json:"bitmapSeq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInt) Reset()         { *m = RequestInt{} }
func (m *RequestInt) String() string { return proto.CompactTextString(m) }
func (*RequestInt) ProtoMessage()    {}
func (*RequestInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_GrpcService_dc7e8bd139018203, []int{0}
}
func (m *RequestInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInt.Unmarshal(m, b)
}
func (m *RequestInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInt.Marshal(b, m, deterministic)
}
func (dst *RequestInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInt.Merge(dst, src)
}
func (m *RequestInt) XXX_Size() int {
	return xxx_messageInfo_RequestInt.Size(m)
}
func (m *RequestInt) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInt.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInt proto.InternalMessageInfo

func (m *RequestInt) GetOutInt() string {
	if m != nil {
		return m.OutInt
	}
	return ""
}

type ResponseInt struct {
	OutInt               int64    `protobuf:"varint,2,opt,name=outInt" json:"outInt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseInt) Reset()         { *m = ResponseInt{} }
func (m *ResponseInt) String() string { return proto.CompactTextString(m) }
func (*ResponseInt) ProtoMessage()    {}
func (*ResponseInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_GrpcService_dc7e8bd139018203, []int{1}
}
func (m *ResponseInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInt.Unmarshal(m, b)
}
func (m *ResponseInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInt.Marshal(b, m, deterministic)
}
func (dst *ResponseInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInt.Merge(dst, src)
}
func (m *ResponseInt) XXX_Size() int {
	return xxx_messageInfo_ResponseInt.Size(m)
}
func (m *ResponseInt) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInt.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInt proto.InternalMessageInfo

func (m *ResponseInt) GetOutInt() int64 {
	if m != nil {
		return m.OutInt
	}
	return 0
}

type Request struct {
	OutBuf               string   `protobuf:"bytes,3,opt,name=outBuf" json:"outBuf,omitempty"`
	BitmapSeq            string   `protobuf:"bytes,6,opt,name=bitmapSeq" json:"bitmapSeq,omitempty"`
	Next                 string   `protobuf:"bytes,1,opt,name=next" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_GrpcService_dc7e8bd139018203, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetOutBuf() string {
	if m != nil {
		return m.OutBuf
	}
	return ""
}

type Response struct {
	OutBuf               string   `protobuf:"bytes,4,opt,name=outBuf" json:"outBuf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_GrpcService_dc7e8bd139018203, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOutBuf() string {
	if m != nil {
		return m.OutBuf
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestInt)(nil), "GrpcServices.RequestInt")
	proto.RegisterType((*ResponseInt)(nil), "GrpcServices.ResponseInt")
	proto.RegisterType((*Request)(nil), "GrpcServices.Request")
	proto.RegisterType((*Response)(nil), "GrpcServices.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GetSequenceIntService service

type GetSequenceIntServiceClient interface {
	GrpcGetSequenceInt(ctx context.Context, in *RequestInt, opts ...grpc.CallOption) (*ResponseInt, error)
}

type getSequenceIntServiceClient struct {
	cc *grpc.ClientConn
}

func NewGetSequenceIntServiceClient(cc *grpc.ClientConn) GetSequenceIntServiceClient {
	return &getSequenceIntServiceClient{cc}
}

func (c *getSequenceIntServiceClient) GrpcGetSequenceInt(ctx context.Context, in *RequestInt, opts ...grpc.CallOption) (*ResponseInt, error) {
	out := new(ResponseInt)
	err := grpc.Invoke(ctx, "/GrpcServices.GetSequenceIntService/GrpcGetSequenceInt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetSequenceIntService service

type GetSequenceIntServiceServer interface {
	GrpcGetSequenceInt(context.Context, *RequestInt) (*ResponseInt, error)
}

func RegisterGetSequenceIntServiceServer(s *grpc.Server, srv GetSequenceIntServiceServer) {
	s.RegisterService(&_GetSequenceIntService_serviceDesc, srv)
}

func _GetSequenceIntService_GrpcGetSequenceInt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetSequenceIntServiceServer).GrpcGetSequenceInt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcServices.GetSequenceIntService/GrpcGetSequenceInt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetSequenceIntServiceServer).GrpcGetSequenceInt(ctx, req.(*RequestInt))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetSequenceIntService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcServices.GetSequenceIntService",
	HandlerType: (*GetSequenceIntServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcGetSequenceInt",
			Handler:    _GetSequenceIntService_GrpcGetSequenceInt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GrpcService.proto",
}

// Client API for GetSequenceService service

type GetSequenceServiceClient interface {
	GrpcGetSequence(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getSequenceServiceClient struct {
	cc *grpc.ClientConn
}

func NewGetSequenceServiceClient(cc *grpc.ClientConn) GetSequenceServiceClient {
	return &getSequenceServiceClient{cc}
}

func (c *getSequenceServiceClient) GrpcGetSequence(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/GrpcServices.GetSequenceService/GrpcGetSequence", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetSequenceService service

type GetSequenceServiceServer interface {
	GrpcGetSequence(context.Context, *Request) (*Response, error)
}

func RegisterGetSequenceServiceServer(s *grpc.Server, srv GetSequenceServiceServer) {
	s.RegisterService(&_GetSequenceService_serviceDesc, srv)
}

func _GetSequenceService_GrpcGetSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetSequenceServiceServer).GrpcGetSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcServices.GetSequenceService/GrpcGetSequence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetSequenceServiceServer).GrpcGetSequence(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetSequenceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcServices.GetSequenceService",
	HandlerType: (*GetSequenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcGetSequence",
			Handler:    _GetSequenceService_GrpcGetSequence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GrpcService.proto",
}

func init() { proto.RegisterFile("GrpcService.proto", fileDescriptor_GrpcService_dc7e8bd139018203) }

var fileDescriptor_GrpcService_dc7e8bd139018203 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x74, 0x2f, 0x2a, 0x48,
	0x0e, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x41,
	0x12, 0x2a, 0x56, 0x52, 0xe1, 0xe2, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xf1, 0xcc, 0x2b,
	0x11, 0x12, 0xe3, 0x62, 0xcb, 0x2f, 0x05, 0xb1, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0,
	0x3c, 0x25, 0x55, 0x2e, 0xee, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x54, 0x65, 0x4c,
	0x0a, 0x8c, 0x1a, 0xcc, 0x70, 0x65, 0x8a, 0x5c, 0xec, 0x50, 0xc3, 0xa0, 0x4a, 0x9c, 0x4a, 0xd3,
	0x24, 0x98, 0xe1, 0x26, 0x39, 0x95, 0xa6, 0x29, 0x29, 0x71, 0x71, 0xc0, 0x4c, 0x42, 0x52, 0xc3,
	0x82, 0xac, 0xc6, 0x28, 0x85, 0x4b, 0xd4, 0x3d, 0xb5, 0x24, 0x18, 0x64, 0x52, 0x5e, 0x32, 0xc8,
	0x42, 0xa8, 0x6b, 0x85, 0xbc, 0xb9, 0x84, 0x40, 0x8e, 0x47, 0x95, 0x14, 0x92, 0xd0, 0x43, 0xf6,
	0x91, 0x1e, 0xc2, 0x3b, 0x52, 0x92, 0xe8, 0x32, 0x70, 0x2f, 0x28, 0x31, 0x18, 0x45, 0x70, 0x09,
	0x21, 0x19, 0x04, 0xb3, 0xc2, 0x89, 0x8b, 0x1f, 0xcd, 0x0a, 0x21, 0x51, 0xac, 0xe6, 0x4b, 0x89,
	0x61, 0x37, 0x5c, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0xd0, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xaa, 0xae, 0xd2, 0xce, 0x7d, 0x01, 0x00, 0x00,
}
